# Define the default driver
#webdriver.driver=phantomjs
 
# Appears at the top of the reports
serenity.project.name = Demo Project using Serenity and JUnit

webdriver.autodownload = false
webdriver.driver = chrome
headless.mode = false
chrome.switches = --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage

webdriver.chrome.driver = chromedriver-mac-arm64/chromedriver
# webdriver.chrome.bin = /usr/bin/google-chrome

webdriver.wait.for.timeout = 15000
serenity.timeout = 15000
serenity.webdriver.timeouts.implicitlywait = 5000
# Pentru Firefox se descarca ultima versiune geckodriver.
# Pentru Chrome se deverifica daca ultima versiune (sau cea stabila) a chromedriver este buna. Altfel, se foloseste o versiune anterioara.


# Root package for any JUnit acceptance tests
serenity.test.root=webFTP.features

# Customise your riequirements hierarchy
#serenity.requirement.types=feature, story

# Run the tests without calling webdriver - useful to check your JUnit wireing
#serenity.dry.run=true

# Customise browser size
#serenity.browser.height = 1200
#serenity.browser.width = 1200


